# Generated by Django 5.2.6 on 2025-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опции')),
                ('category', models.CharField(blank=True, help_text='Например: Салон, Комфорт, Безопасность', max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('generation', models.CharField(blank=True, max_length=100, verbose_name='Поколение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (руб.)')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('hatchback', 'Хэтчбек'), ('liftback', 'Лифтбек'), ('coupe', 'Купе'), ('estate', 'Универсал'), ('minivan', 'Минивэн'), ('pickup', 'Пикап')], max_length=10, verbose_name='Тип кузова')),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electro', 'Электро')], max_length=10, verbose_name='Тип двигателя')),
                ('engine_volume', models.FloatField(verbose_name='Объем двигателя (л)')),
                ('engine_power', models.PositiveSmallIntegerField(verbose_name='Мощность (л.с.)')),
                ('transmission', models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('robot', 'Роботизированная'), ('variator', 'Вариатор')], max_length=10, verbose_name='Коробка передач')),
                ('drive', models.CharField(choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], max_length=3, verbose_name='Привод')),
                ('condition', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('satisfactory', 'Удовлетворительное')], default='good', max_length=15, verbose_name='Состояние')),
                ('owners', models.PositiveSmallIntegerField(default=1, verbose_name='Количество владельцев')),
                ('documents', models.CharField(default='Без ограничений', max_length=100, verbose_name='Документы')),
                ('steering', models.CharField(choices=[('left', 'Левый'), ('right', 'Правый')], default='left', max_length=10, verbose_name='Руль')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('characteristics', models.ManyToManyField(blank=True, to='catalog.characteristic', verbose_name='Дополнительные характеристики')),
                ('features', models.ManyToManyField(blank=True, to='catalog.feature', verbose_name='Опции и комплектации')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
