# Generated by Django 5.2.6 on 2025-09-06 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_carphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAgreementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_full_name', models.CharField(max_length=200, verbose_name='ФИО покупателя')),
                ('buyer_passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('buyer_passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('buyer_passport_issued', models.TextField(verbose_name='Кем и когда выдан паспорт')),
                ('buyer_registration_address', models.TextField(verbose_name='Адрес регистрации')),
                ('seller_full_name', models.CharField(max_length=200, verbose_name='ФИО продавца')),
                ('seller_passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта продавца')),
                ('seller_passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта продавца')),
                ('seller_passport_issued', models.TextField(verbose_name='Кем и когда выдан паспорт продавца')),
                ('seller_registration_address', models.TextField(verbose_name='Адрес регистрации продавца')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('car_year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('car_vin', models.CharField(blank=True, max_length=17, verbose_name='VIN номер')),
                ('car_license_plate', models.CharField(blank=True, max_length=9, verbose_name='Гос номер')),
                ('car_price', models.PositiveIntegerField(verbose_name='Цена автомобиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заявка на договор',
                'verbose_name_plural': 'Заявки на договоры',
            },
        ),
    ]
