# Generated by Django 5.2.6 on 2025-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_purchaseagreementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseagreementrequest',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон покупателя'),
        ),
        migrations.AddField(
            model_name='purchaseagreementrequest',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон продавца'),
        ),
    ]
