# Generated by Django 4.2.24 on 2025-09-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_purchaseagreementrequest_buyer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('japan', 'Япония'), ('germany', 'Германия'), ('korea', 'Корея'), ('usa', 'США'), ('france', 'Франция'), ('italy', 'Италия'), ('russia', 'Россия'), ('other', 'Другая')], default='other', max_length=10, verbose_name='Страна'),
        ),
    ]
