# Generated by Django 4.2.24 on 2025-10-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_car_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('inspection_date', models.DateField(verbose_name='Дата осмотра')),
                ('inspection_time', models.CharField(choices=[('09:00-10:00', '09:00 - 10:00'), ('10:00-11:00', '10:00 - 11:00'), ('11:00-12:00', '11:00 - 12:00'), ('12:00-13:00', '12:00 - 13:00'), ('13:00-14:00', '13:00 - 14:00'), ('14:00-15:00', '14:00 - 15:00'), ('15:00-16:00', '15:00 - 16:00'), ('16:00-17:00', '16:00 - 17:00')], max_length=20, verbose_name='Время осмотра')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заявка на осмотр',
                'verbose_name_plural': 'Заявки на осмотр',
                'ordering': ['-created_at'],
            },
        ),
    ]
