# Generated by Django 4.2.24 on 2025-10-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_inspectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Телефон для связи'),
        ),
    ]
