# Generated by Django 4.2.24 on 2025-10-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_car_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='contact_phone',
        ),
    ]
