# Generated by Django 4.2.24 on 2025-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_car_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='carphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
